[project]
name = "dify-plugin-aws-sns"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.40.21",
    "dify-plugin>=0.4.4",
]
